In [1]:
import torch
import torecsys as trs

In [2]:
# multi_0 = trs.inputs.base.MultiIndicesFieldAwareEmbedding(8, [16, 16, 16])
# multi_0.set_schema(inputs=["m0"])

# m0 = torch.randint(0, 16, size=(8, 3))
# m0.names = ("B", "N")

# emb_m = multi_0(m0)

# val_0 = trs.inputs.base.SingleIndexEmbedding(1, 16)
# val_1 = trs.inputs.base.SingleIndexEmbedding(1, 16)
# single_0 = trs.inputs.base.SingleIndexEmbedding(8, 16)
# single_1 = trs.inputs.base.SingleIndexEmbedding(8, 16)

# val_0.set_schema(inputs=["t0"])
# val_1.set_schema(inputs=["t1"])
# single_0.set_schema(inputs=["t0"])
# single_1.set_schema(inputs=["t1"])

# val_stack = trs.inputs.base.StackedInputs(inputs=[val_0, val_1])
# single_stack = trs.inputs.base.StackedInputs(inputs=[single_0, single_1])

# inputs_wrapper = trs.inputs.InputsWrapper({
#     "feat_inputs": val_stack,
#     "emb_inputs": single_stack
# })

# t0 = torch.randint(0, 16, size=(8, 1))
# t1 = torch.randint(0, 16, size=(8, 1))
# t0.names = ("B", "N")
# t1.names = ("B", "N")

# inp = {"t0": t0, "t1": t1}

# emb_inp = inputs_wrapper(inp)

In [3]:
user_feat = torch.randn(size=(4, 1, 3))
content_feat = torch.randn(size=(4, 1, 3))
pos_feat = torch.randn(size=(4, 1, 3))
neg_feat = torch.randn(size=(4, 2, 3))

names = ("B", "N", "E")

user_feat.names = names
content_feat.names = names
pos_feat.names = names
neg_feat.names = names

..\c10/core/TensorImpl.h:864: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


In [4]:
model = trs.models.DeepMatchingCorrelationPredictionModel(3, 1, 1, 1, 1, [3, 3], [3, 3], [3, 3])

C:\Users\User\Desktop\projects\torecsys\torecsys\utils\decorator\decorator.py:41: UserWarning: The module is checked that it is not compatible with torch.jit.trace due to the NamedTensor method. This will be updated to compatibilized when PyTorch update.
  "when PyTorch update.", UserWarning


In [5]:
output = model(user_feat, content_feat, pos_feat, neg_feat)

In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
loss_pred = torch.nn.MSELoss()
loss_match = torch.nn.MSELoss()
loss_corr = torch.nn.MSELoss()

In [11]:
loss = loss_pred(output[0], torch.zeros(size=(4, 1)))

In [12]:
loss.backward()

In [13]:
for p in model.parameters():
    print(p.grad)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([0.0086, 0.0000, 0.0000])
tensor([[-0.0053,  0.0000,  0.0000]])
tensor([0.0199])
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


In [14]:
loss = loss_pred(output[1], torch.zeros(size=(4, 1)))

In [15]:
loss.backward()

In [16]:
for p in model.parameters():
    print(p.grad)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([0.0086, 0.0000, 0.0000])
tensor([[-0.0053,  0.0000,  0.0000]])
tensor([0.0199])
tensor([[ 0.0050,  0.0031, -0.0003],
        [-0.0110, -0.0070,  0.0024],
        [ 0.0000,  0.0000,  0.0000]])
tensor([-0.0076,  0.0066,  0.0000])
tensor([[ 3.8231e-03,  6.6994e-04,  0.0000e+00],
        [-5.4403e-04,  0.0000e+00,  0.0000e+00],
        [-5.0403e-04, -3.4585e-05,  0.0000e+00]])
tensor([ 0.0345, -0.0072, -0.0023])
tensor([[-0.0091, -0.0026, -0.0235]])
tensor([-0.1244])
tensor([[-0.0054,  0.0018, -0.0046],
        [ 0.0020, -0.0017,  0.0020],
        [-0.0013,  0.0001, -0.0005]])
tensor([-0.0077,  0.0035, -0.0018])
tensor([[-0.0179, -0.0022, -0.0011],
        [ 0.0026,  0.0003,  0.0002],
        [-0.0137, -0.0017, -0.0009]])
tensor([-0.0175,  0.0026, -0.0134])
tensor([[0.0182, 0.0082, 0.0247]])
te

In [17]:
loss = loss_pred(output[2], torch.zeros(size=(4, 1)))

In [18]:
loss.backward()

In [19]:
for p in model.parameters():
    print(p.grad)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([0.0086, 0.0000, 0.0000])
tensor([[-0.0053,  0.0000,  0.0000]])
tensor([0.0199])
tensor([[ 0.0050,  0.0031, -0.0003],
        [-0.0110, -0.0070,  0.0024],
        [ 0.0000,  0.0000,  0.0000]])
tensor([-0.0076,  0.0066,  0.0000])
tensor([[ 3.8231e-03,  6.6994e-04,  0.0000e+00],
        [-5.4403e-04,  0.0000e+00,  0.0000e+00],
        [-5.0403e-04, -3.4585e-05,  0.0000e+00]])
tensor([ 0.0345, -0.0072, -0.0023])
tensor([[-0.0091, -0.0026, -0.0235]])
tensor([-0.1244])
tensor([[-0.0054,  0.0018, -0.0046],
        [ 0.0020, -0.0017,  0.0020],
        [-0.0013,  0.0001, -0.0005]])
tensor([-0.0077,  0.0035, -0.0018])
tensor([[-0.0179, -0.0022, -0.0011],
        [ 0.0026,  0.0003,  0.0002],
        [-0.0137, -0.0017, -0.0009]])
tensor([-0.0175,  0.0026, -0.0134])
tensor([[0.0182, 0.0082, 0.0247]])
te